name: Setup Linux dependencies

runs:
  using: composite

  steps:
    - name: Install host dependencies
      shell: bash
      run: |
        sudo apt-get -y update
        sudo apt-get -y install \
          dpkg-dev \
          ninja-build extra-cmake-modules scdoc \
          libopengl0 libxcb-cursor-dev

    - name: Setup AppImage tooling
      shell: bash
      run: |
        # Determinate AppImage architecture to use
        dpkg_arch="$(dpkg-architecture -q DEB_HOST_ARCH_CPU)"
        case "$dpkg_arch" in
          "amd64")
            APPIMAGE_ARCH="x86_64"
            ;;
          "arm64")
            APPIMAGE_ARCH="aarch64"
            ;;
          *)
            echo "# 🚨 The Debian architecture \"$deb_arch\" is not recognized!" >> "$GITHUB_STEP_SUMMARY"
            exit 1
            ;;
        esac

        mkdir -p ~/bin
        curl -Lo ~/bin/appimagetool https://github.com/probonopd/go-appimage/releases/download/continuous/appimagetool-907-"$APPIMAGE_ARCH".AppImage
        chmod +x ~/bin/appimagetool
        echo "$HOME/bin" >> "$GITHUB_PATH"

        # NOTE(@getchoo): Ubuntu's version of Appstream (as of 2025-11-07) is too old to validate our file, so try to skip it
        sudo apt purge --autoremove appstream
